GET http://localhost:5235/doctors

###
GET http://localhost:5235/doctors/1

###
POST http://localhost:5235/doctors
Content-Type: application/json

{
    "name" : "Krasutska Diana Hryhorivna",
    "gender" : "Female",
    "username" : "krasutskaaa",
    "password" : "qwerty89",
    "specialization" : "Surgeon"
}

###
PUT  http://localhost:5235/doctors/3
Content-Type: application/json

{
    "name" : "Vashchenko Valeriya Petrivna",
    "gender" : "Female",
    "username" : "vashchEnKo49",
    "password" : "emitedXrays",
    "specialization" : "Radiologist"
}

###
DELETE http://localhost:5235/doctors/4