GET http://localhost:5235/patients

###
GET http://localhost:5235/patients/1

###
POST http://localhost:5235/patients
Content-Type: application/json

{
    "name" : "Fiyalo Dmytro Ivanovych",
    "gender" : "Male",
    "birthday" : "1981-05-03"
}


###
PUT http://localhost:5235/patients/3
Content-type: application/json

{
    "name" : "Fiyalo Dmytro Ivanovych",
    "gender" : "Male",
    "birthday" : "1981-05-05"
}

###
DELETE http://localhost:5235/patients/2
