GET http://localhost:5235/tests

###
GET http://localhost:5235/tests/1

###
POST http://localhost:5235/tests
Content-Type: application/json

{
    
    "patientId" : "81CEF3E6-B132-4774-8031-40EFF2772B6E",
    "doctorId" : "9801CC8D-C5ED-4850-B3DC-48A6C9B09C91",
    "Name" : "RedBloodCellCount",
    "Value" : 4.7e6,
    "MinValue" : 4.35e6,
    "MaxValue" : 5.65e6,
    "UMeasurement" : "cells/mcL" 
}


###
PUT http://localhost:5235/tests/5
Content-type: application/json

{
    "patientId" : 1,
    "doctorId" : 5,
    "Name" : "WhiteBloodCellCount",
    "Value" : 6e9,
    "MinValue" : 4.5e9,
    "MaxValue" : 11e9,
    "UMeasurement" : "cells/L"
    
    
}

###
DELETE http://localhost:5235/tests/6
